# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.5
  - nightly
notifications:
  email: false
branches:
  only: master
matrix:
  allow_failures:
    - julia: nightly
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("AdaptiveDistanceFields")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
