# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.5
  - nightly
notifications:
  email: false
branches:
  only: master
matrix:
  allow_failures:
    - julia: nightly
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone("https://github.com/rdeits/EnhancedGJK.jl.git")'
 - julia -e 'Pkg.clone(pwd()); Pkg.build("AdaptiveDistanceFields"); Pkg.test("AdaptiveDistanceFields"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("AdaptiveDistanceFields")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("AdaptiveDistanceFields")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
